[build-system]
requires = [
  "setuptools>=46.4",
  "wheel",
]


[tool.black]
line-length = 100
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.tox
  | \.venv
  | \.cache
  | _build
  | build
  | dist
)/
'''
